//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ShoppingList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ab_admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ab_admin()
        {
            this.ab_category = new HashSet<ab_category>();
            this.ab_product = new HashSet<ab_product>();
        }
    
        public int ab_admin_id { get; set; }
        public string ab_admin_name { get; set; }
        public string ab_admin_surname { get; set; }
        public string ab_admin_full_name { get; set; }
        public string ab_admin_mail { get; set; }
        public string ab_admin_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ab_category> ab_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ab_product> ab_product { get; set; }
    }
}
