//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ShoppingList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ab_product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_image { get; set; }
        public string product_desc { get; set; }
        public Nullable<int> product_price { get; set; }
        public Nullable<int> product_fk_cat { get; set; }
        public Nullable<int> product_fk_admin { get; set; }
    
        public virtual ab_admin ab_admin { get; set; }
        public virtual ab_category ab_category { get; set; }
    }
}
