//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ShoppingList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ab_user
    {
        public int ab_user_id { get; set; }
        public string ab_user_name { get; set; }
        public string ab_user_surname { get; set; }
        public string ab_user_full_name { get; set; }
        public string ab_user_email { get; set; }
        public string ab_user_password { get; set; }
    }
}
